import { Geist, Geist_Mono } from "next/font/google";
import "../app/styles/globals.css";
import "../app/styles/responsive.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",   
  preload: false,   
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",   
  preload: false, 
});

export const metadata = {
  title: "wrcclinic",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: '/img/favicons/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
      { url: '/img/favicons/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
      { url: '/img/favicons/android-chrome-192x192.png', sizes: '192x192', type: 'image/png' },
      { url: '/img/favicons/android-chrome-512x512.png', sizes: '512x512', type: 'image/png' },
    ],
    apple: '/img/favicons/apple-touch-icon.png',
    shortcut: '/img/favicons/favicon-32x32.png',
    mask: { url: '/img/favicons/safari-pinned-tab.svg', color: '#5bbad5' },
  },
  manifest: '/img/favicons/site.webmanifest',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ka" data-scroll-behavior="smooth">
      <head>
        {/* Font Awesome */}
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          rel="stylesheet"
        />
        {/* MS Tile Color */}
        <meta name="msapplication-TileColor" content="#2b5797" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
